// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeServicios.Data;

#nullable disable

namespace SistemaDeServicios.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260506011819_EliminarServiciosYRelacionarTipoServicio")]
    partial class EliminarServiciosYRelacionarTipoServicio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaDeServicios.Modelos.Departamentos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DireccionId")
                        .HasColumnType("int");

                    b.Property<int>("DirecionId")
                        .HasColumnType("int");

                    b.Property<string>("NombreDep")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.Direcciones", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreDir")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Direcciones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreDir = "Despacho del Alcalde"
                        },
                        new
                        {
                            Id = 2,
                            NombreDir = "Dirección General"
                        },
                        new
                        {
                            Id = 3,
                            NombreDir = "Asuntos Públicos"
                        },
                        new
                        {
                            Id = 4,
                            NombreDir = "Atención al Ciudadano"
                        },
                        new
                        {
                            Id = 5,
                            NombreDir = "Prensa y Ciudadano"
                        },
                        new
                        {
                            Id = 6,
                            NombreDir = "Gestión Urbana"
                        },
                        new
                        {
                            Id = 7,
                            NombreDir = "Obras"
                        },
                        new
                        {
                            Id = 8,
                            NombreDir = "Servicios Generales"
                        },
                        new
                        {
                            Id = 9,
                            NombreDir = "Planeamiento Urbano"
                        },
                        new
                        {
                            Id = 10,
                            NombreDir = "Catastro"
                        },
                        new
                        {
                            Id = 11,
                            NombreDir = "Seguridad Ciudadana"
                        },
                        new
                        {
                            Id = 12,
                            NombreDir = "Protección Civil"
                        },
                        new
                        {
                            Id = 13,
                            NombreDir = "Gestión Social"
                        },
                        new
                        {
                            Id = 14,
                            NombreDir = "CMDNNA"
                        },
                        new
                        {
                            Id = 15,
                            NombreDir = "Administración y Finanzas"
                        },
                        new
                        {
                            Id = 16,
                            NombreDir = "Planificación de Presupuesto"
                        },
                        new
                        {
                            Id = 17,
                            NombreDir = "Recursos Humanos"
                        },
                        new
                        {
                            Id = 18,
                            NombreDir = "Administración Tributaria"
                        },
                        new
                        {
                            Id = 19,
                            NombreDir = "Tecnología y Sistemas"
                        },
                        new
                        {
                            Id = 20,
                            NombreDir = "Deportes"
                        },
                        new
                        {
                            Id = 21,
                            NombreDir = "IMASUR"
                        },
                        new
                        {
                            Id = 22,
                            NombreDir = "Registro Civil"
                        },
                        new
                        {
                            Id = 23,
                            NombreDir = "Tesorería Municipal"
                        },
                        new
                        {
                            Id = 24,
                            NombreDir = "Sindicatura Municipal"
                        },
                        new
                        {
                            Id = 25,
                            NombreDir = "Cultura"
                        },
                        new
                        {
                            Id = 26,
                            NombreDir = "Instituto Municipal de la Vivienda"
                        },
                        new
                        {
                            Id = 27,
                            NombreDir = "Consultoría Jurídica"
                        },
                        new
                        {
                            Id = 28,
                            NombreDir = "Cámara Municipal"
                        });
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.Equipos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detalles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DireccionId")
                        .HasColumnType("int");

                    b.Property<int>("DirecionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.ToTable("Equipos");
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.HojaServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caracteristicas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sugerencias")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HojasDeServicio");
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.TipoServicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("HojaServicioId")
                        .HasColumnType("int");

                    b.Property<bool>("Recurrente")
                        .HasColumnType("bit");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HojaServicioId");

                    b.ToTable("TiposDeServicios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Recurrente = true,
                            Texto = "Mantenimiento de Impresora"
                        },
                        new
                        {
                            Id = 2,
                            Recurrente = true,
                            Texto = "Formateo de Equipo"
                        },
                        new
                        {
                            Id = 3,
                            Recurrente = true,
                            Texto = "Mantenimiento preventivo y/o correctivo"
                        },
                        new
                        {
                            Id = 4,
                            Recurrente = true,
                            Texto = "Instalación y Actualización de Software"
                        },
                        new
                        {
                            Id = 5,
                            Recurrente = true,
                            Texto = "Instalación y/o Configuración de Impresora"
                        },
                        new
                        {
                            Id = 6,
                            Recurrente = true,
                            Texto = "Instalación de Dispositivos Internos del CPU"
                        },
                        new
                        {
                            Id = 7,
                            Recurrente = true,
                            Texto = "Configuración del Sistema Operativo"
                        },
                        new
                        {
                            Id = 8,
                            Recurrente = true,
                            Texto = "Respaldo de Información"
                        },
                        new
                        {
                            Id = 9,
                            Recurrente = true,
                            Texto = "Configuración de Red"
                        });
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DireccionId")
                        .HasColumnType("int");

                    b.Property<int>("DirecionId")
                        .HasColumnType("int");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DireccionId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.Departamentos", b =>
                {
                    b.HasOne("SistemaDeServicios.Modelos.Direcciones", "Direccion")
                        .WithMany("Departamentos")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.Equipos", b =>
                {
                    b.HasOne("SistemaDeServicios.Modelos.Direcciones", "Direccion")
                        .WithMany("Equipos")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.TipoServicio", b =>
                {
                    b.HasOne("SistemaDeServicios.Modelos.HojaServicio", null)
                        .WithMany("Servicios")
                        .HasForeignKey("HojaServicioId");
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.Usuarios", b =>
                {
                    b.HasOne("SistemaDeServicios.Modelos.Direcciones", "Direccion")
                        .WithMany("Usuarios")
                        .HasForeignKey("DireccionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direccion");
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.Direcciones", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("Equipos");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("SistemaDeServicios.Modelos.HojaServicio", b =>
                {
                    b.Navigation("Servicios");
                });
#pragma warning restore 612, 618
        }
    }
}
